### ISSUE TITLE
Essentials

### ISSUE THREAD

**Issue by SEAPUNK** [turnfm/tracker#2]
Basically, get the simple stuff going, which includes (but is not limited to)

* Login/Logout
  - Twitter
  - Facebook
* Dashboard
* Playlist management
  - Youtube
  - Soundcloud
  - Importing
  - Editing
* Player
  - Youtube
  - Soundcloud
  - *Maybe* visualizers?
* Chat
* Moderation
* Administration
* so on and so forth

**Comment by schisma** [comment]
i hope you do this in php

**Comment by schisma** [comment]
its best to use codeigniter and typo3, its a good combo

**Comment by schisma** [comment]
and then connect it with a java backend using gradle to build

**Comment by schisma** [comment]
i would like to buy shares for this project, it looks like it has a bright future ahead of it

**Comment by SEAPUNK** [comment]
@schisma Please keep your memes elsewhere.
