### ISSUE TITLE
important features that might not have been touched in top thread

### ISSUE THREAD

**Issue by robotoid** [turnfm/tracker#4]
what turn.dj needs are:
a volume bar
a mute button
a way to see what you play next without going into your lists

what turn.dj would look nice having:
a progress bar

http://i.imgur.com/NMrwkt2.png

**Comment by SEAPUNK** [comment]
A volume bar/mute button are going to be directly overlayed on the video.

What you play next is already implemented, see: http://i.imgur.com/JwtnSYb.png

**Comment by Uricorn** [comment]
Not a big fan of progress bars when there is a time till song ends ticker, which as far as I can tell is missing. (RCS had the option to disable such a progress bar.)

**Comment by SEAPUNK** [comment]
I might turn it into a setting, or fit it somewhere in the UI. The progress bar is for the moderators, mostly, so they can seek a video for everyone to a certain point.

**Comment by Uricorn** [comment]
Oh that's an interesting feature, if it has a use then I am not against it.

Though I can't see mods using it for music without knowing that the song about to play needs to start a few seconds later. For music it would be better to set a start and end time in the song playlist. (but there are many issues with that too)

**Comment by SEAPUNK** [comment]
There are certain communities that don't just play music. I'm also toying with the idea of the DJ being able to skip forward, but not seek back, where the mods can do both.

**Comment by Uricorn** [comment]
Would be a shame if 10 hour NyanCat stopped playing. +1 for seek back ability.

Seriously though, features like these should be made with the ability for the host to toggle them. (Even if you don't actually give them that setting at first.)

You never know what kind of bugs/abuse might show up when you give every user some extra power.

**Comment by SEAPUNK** [comment]
Bugs won't be a problem, we'll plow through them. I trust my backend developer to do a good job, and a good job at fixing problems. I'll add the option to toggle the mod seek, though, good idea.
